name: Feature request
description: Suggest an improvement or a new capability
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: What problem does this solve? Why is it valuable?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the desired CLI/API behavior and expected outputs.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative approaches or tools you evaluated?
    validations:
      required: false
